# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: shop_demo
  pool: 5
  timeout: 5000
  username: emkey
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: shop_demo
  pool: 5
  timeout: 5000
  username: emkey
  password:
